name: Android CI

on:
  push:
    branches: [ "main" ]  # 当你推送到 master 分支时触发
  workflow_dispatch:  # 也可以手动触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # 根据你的项目需求选择合适的 Java 版本
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew assembleDebug  # 编译调试版本的 APK
        ./gradlew --stop

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk  # 上传生成的 APK 文件
